baseURL = 'https://anadeap.github.io/dwes/'
languageCode = 'en-us'
title = 'Documentación DWES'
theme = "learn"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
[outputs]
home = ["HTML","RSS","JSON"]
[params]
themeVariant = "dwes"

[Languages]
   [Languages.es]
   title = "DWES Español"
   weight = 1
   languageName = "Español"
   landingPageURL = "http://cpilosenlaces.com"
   landingPageName = "<i class = 'fas fa-university'></i>CPI Los Enlaces"
   ContentDir = "content"
   [[Languages.es.menu.shortcuts]]
   name = "<i class=fa fa-github'></i>   Web de Github"
   identified=""
   url="https://github.com/matcornic/hugo-theme-learn"
   weight = 1
   [[Languages.es.menu.shortcuts]]
   name = "<i class=fa fa-bookmark'></i>   Web de Hugo"
   identified=""
   url="https://gohugo.io/"
   weight = 2
   [[Languages.es.menu.shortcuts]]
   name = "<i class=fa fa-php'></i>   Web de PHP"
   identified=""
   url="https://php.net"
   weight = 3
   [[Languages.es.menu.shortcuts]]
   name = "<i class=fa fa-wikipedia'></i>   Wiki de DWES"
   identified=""
   url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
   weight = 4
   [Languages.en]
   title = "DWES English"
   weight = 2
   languageName = "English"
   landingPageURL = "http://cpilosenlaces.com"
   landingPageName = "<i class = 'fas fa-university'></i>INSTITUTE Los Enlaces"
   ContentDir = "content"
   [[Languages.en.menu.shortcuts]]
   name = "<i class=fa fa-github'></i>   Github web"
   identified=""
   url="https://github.com/matcornic/hugo-theme-learn"
   weight = 1
   [[Languages.en.menu.shortcuts]]
   name = "<i class=fa fa-bookmark'></i>   Hugo web"
   identified=""
   url="https://gohugo.io/"
   weight = 2
   [[Languages.en.menu.shortcuts]]
   name = "<i class=fa fa-php'></i>   PHP web"
   identified=""
   url="https://php.net"
   weight = 3
   [[Languages.en.menu.shortcuts]]
   name = "<i class=fa fa-wikipedia'></i>   Wiki of DWES"
   identified=""
   url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
   weight = 4
   [Languages.fr]
   title = "DWES Francais"
   weight = 3
   languageName = "Francais"
   landingPageURL = "http://cpilosenlaces.com"
   landingPageName = "<i class = 'fas fa-university'></i>LYCÉE Los Enlaces"
   ContentDir = "content"
   [[Languages.fr.menu.shortcuts]]
   name = "<i class=fa fa-github'></i>   Site Github"
   identified=""
   url="https://github.com/matcornic/hugo-theme-learn"
   weight = 1
   [[Languages.fr.menu.shortcuts]]
   name = "<i class=fa fa-bookmark'></i>   Site Hugo"
   identified=""
   url="https://gohugo.io/"
   weight = 2
   [[Languages.fr.menu.shortcuts]]
   name = "<i class=fa fa-php'></i>   Site PHP"
   identified=""
   url="https://php.net"
   weight = 3
   [[Languages.fr.menu.shortcuts]]
   name = "<i class=fa fa-wikipedia'></i>   Wiki DWES"
   identified=""
   url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
   weight = 4

